name: 'Format version'
description: 'Format version'
outputs:
  version:
    description: Version number of the image released to ECR
    value: ${{ steps.format-version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: format-version
      name: "Format version"
      shell: bash
      run: |
        set -eu
        
        REF_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}
        if [ "$REF_NAME" = "main" ] || [ "$REF_NAME" = "master" ]; then
          currentDate=$(date +"%Y.%m.%d.%H.%M") ;
          tag=$(echo $GITHUB_SHA | cut -c 1-7) ;
          echo "version=$(echo $currentDate-$tag)" >> $GITHUB_OUTPUT ;
        else
          set -ue ;
          tag=$(echo ${REF_NAME} | cut -c 1-20 | tr / -) ;
          echo "version=$(echo $tag)" >> $GITHUB_OUTPUT ;
        fi