name: 'Setup Build Environment'
description: 'Setup OpenJDK, Checkout, Login to AWS ECR'
inputs:
#  MAVEN_REPO_PUBLIC_URL:
#    description: 'Maven dependency URL'
#    required: true
#  MAVEN_REPO_SNAPSHOTS_URL:
#    description: 'Maven SNAPSHOT deployment URL'
#    required: true
#  MAVEN_REPO_RELEASES_URL:
#    description: 'Maven RELEASE deployment URL'
#    required: true
#  MAVEN_REPO_USER:
#    description: 'Maven repository username'
#    required: true
#  MAVEN_REPO_PASS:
#    description: 'Maven repository password'
#    required: true
  maven-repo-public-url:
    description: 'Maven dependency URL'
    required: true
  maven-repo-snapshots-url:
    description: 'Maven SNAPSHOT deployment URL'
    required: true
  maven-repo-releases-url:
    description: 'Maven RELEASE deployment URL'
    required: true
  maven-repo-user:
    description: 'Maven repository username'
    required: true
  maven-repo-pass:
    description: 'Maven repository password'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-home-cache-cleanup: true

    - name: Cache SonarCloud packages
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Configure Gradle
      shell: bash
      run: |
        set -eu
        
        mkdir -p ~/.gradle
        CONF_FILE=~/.gradle/gradle.properties
        
        echo '# Gradle configuration' > "$CONF_FILE"
        
        echo sympowerMavenRepoPublicUrl=${{ inputs.maven-repo-public-url }} >> "$CONF_FILE"
        echo sympowerMavenRepoSnapshotsUrl=${{ inputs.maven-repo-snapshots-url }} >> "$CONF_FILE"
        echo sympowerMavenRepoReleasesUrl={{ inputs.maven-repo-releases-url }} >> "$CONF_FILE"
  
        echo sympowerMavenRepoUsername=${{ inputs.maven-repo-user }} >> "$CONF_FILE"
        echo sympowerMavenRepoPassword=${{ inputs.maven-repo-pass }} >> "$CONF_FILE"

