name: General Build and Push Docker Images to ECR (buildx)
on:
  workflow_call:
    inputs:
      aws_region:
        type: string
        description: "AWS region for ECR"
        required: true
      image_name:
        type: string
        description: "Docker image name"
        required: true
      image_tag:
        type: string
        description: "Docker image tag"
        required: true
      context_path:
        type: string
        description: "Build context path"
        required: true
      dockerfile_path:
        type: string
        description: "Path to the Dockerfile"
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context_path }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_REGISTRY_HOST }}/${{ inputs.image_name }}:${{ inputs.image_tag }}

      - name: Docker image pushed successfully
        run: echo "Docker image pushed successfully to ECR."
