#Release new docker image to ECR and schema to Nexus (if contains any changes)

name: Release new version

on:
  workflow_call:
    inputs:
      gistID:
        required: true
        type: string
    outputs:
      version:
        description: Version number of the image released to ECR
        value: ${{ jobs.build.outputs.version }}
      repository-name:
        description: Name of the repository
        value: ${{ jobs.format-version.outputs.repository-name }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_DEFAULT_BRANCH: ${{ contains('refs/heads/main, refs/heads/master', github.ref) }}
      secrets: ${{ toJSON(secrets) }}
    outputs:
      version: ${{ steps.format-version.outputs.version }}
    steps:
      - id: setup-build-environment
        name: "Setup build environment"
        uses: sympower/sympower-composite-actions/setup-build-environment@v2023.10.30.15.12-299ab4a
        with:
          secrets: ${{ env.secrets }}
      - id: format-version
        name: "Format version"
        uses: sympower/sympower-composite-actions/format-version@v2023.10.30.15.12-299ab4a
        with:
          style-as-release: ${{ env.IS_DEFAULT_BRANCH }}
      - id: run-tests
        name: "Run tests"
        uses: sympower/sympower-composite-actions/run-tests@v2023.10.30.15.12-299ab4a
      - id: code-analysis
        name: "Code analysis"
        uses: sympower/sympower-composite-actions/code-analysis@v2023.10.30.15.12-299ab4a
        with:
          secrets: ${{ env.secrets }}
      - id: build-and-upload-docker-image
        name: "Build and upload Docker Image"
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: sympower/sympower-composite-actions/build-and-upload-docker-image@v2023.10.30.15.12-299ab4a
        with:
          version: ${{ steps.format-version.outputs.version }}
      - name: Update Service Version Badge
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ inputs.gistID }}
          filename: ${{ env.REPOSITORY_NAME }}-service.json
          label: Service Version
          message: ${{ steps.format-version.outputs.version }}
          color: blue
      - id: upload-schema
        name: "Upload schema"
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: sympower/sympower-composite-actions/upload-schema@v2023.10.30.15.12-299ab4a
        with:
          version: ${{ steps.format-version.outputs.version }}
          secrets: ${{ env.secrets }}
          gistID: ${{ inputs.gistID }}
      - id: upload-pacts
        name: "Upload pacts"
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: sympower/sympower-composite-actions/upload-pacts@v2023.10.30.15.12-299ab4a
        with:
          version: ${{ steps.format-version.outputs.version }}
      - id: deploy-staging
        name: "Deploy staging"
        if: env.IS_DEFAULT_BRANCH == 'true'
        uses: sympower/sympower-composite-actions/deploy-to-environment@v2023.10.30.15.12-299ab4a
        with:
          secrets: ${{ env.secrets }}
          version: ${{ steps.format-version.outputs.version }}
          default-name: ${{ env.REPOSITORY_NAME }}
          deploy-group: staging
      - id: upload-build-artifacts
        name: "Upload build artifacts"
        if: always()
        uses: sympower/sympower-composite-actions/upload-build-artifacts@v2023.10.30.15.12-299ab4a
