#Release new docker image to ECR as well as schema (if contains any changes) to Nexus (use for testing ONLY)

name: Release for testing

on:
  workflow_call:
    outputs:
      version:
        description: Version number of the image released to ECR
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - id: setup-build-environment
        name: "Setup build environment"
        uses: sympower/sympower-actions/.github/actions/setup-build-environment@TECH-1140-split-workflow-into-composite-actions
        with:
          secrets: ${{ toJSON(secrets) }}
      - id: build-and-upload-docker-image
        name: "Build and upload Docker Image"
        uses: sympower/sympower-actions/.github/actions/build-and-upload-docker-image@TECH-1140-split-workflow-into-composite-actions
        with:
          secrets: ${{ toJSON(secrets) }}
          version: ${{ steps.setup-build-environment.outputs.version }}
      - id: upload-schema
        name: "Upload schema"
        uses: sympower/sympower-actions/.github/actions/upload-schema@TECH-1140-split-workflow-into-composite-actions
        with:
          secrets: ${{ toJSON(secrets) }}
          version: ${{ steps.setup-build-environment.outputs.version }}
          gistID: "not-used"
      - id: upload-build-artifacts
        name: "Upload build artifacts"
        if: always()
        uses: sympower/sympower-actions/.github/actions/upload-build-artifacts@TECH-1140-split-workflow-into-composite-actions