name: Release new schema version to Nexus

on:
  workflow_call:
    inputs:
      gistID:
        required: true
        type: string
    secrets:
      GIST_SECRET:
        required: true
      MAVEN_REPO_PUBLIC_URL:
        required: true
      MAVEN_REPO_SNAPSHOTS_URL:
        required: true
      MAVEN_REPO_RELEASES_URL:
        required: true
      MAVEN_REPO_USER:
        required: true
      MAVEN_REPO_PASS:
        required: true

jobs:
  release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Cache local gradle repository
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Set env
        run: |
          set -ue ;
          currentDate=$(date +"%Y.%m.%d.%H.%M") ;
          tag=$(echo $GITHUB_SHA | cut -c 1-7) ;
          echo "VERSION=$(echo $currentDate-$tag)" >> $GITHUB_ENV ;
          echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Upload Libraries
        run: |
          set -ue ;
          ./gradlew publish --parallel --continue --stacktrace \
            -PsympowerMavenRepoPublicUrl=${{ secrets.MAVEN_REPO_PUBLIC_URL }} \
            -PsympowerMavenRepoSnapshotsUrl=${{ secrets.MAVEN_REPO_SNAPSHOTS_URL }} \
            -PsympowerMavenRepoReleasesUrl=${{ secrets.MAVEN_REPO_RELEASES_URL }} \
            -PsympowerMavenRepoUsername=${{ secrets.MAVEN_REPO_USER }} \
            -PsympowerMavenRepoPassword=${{ secrets.MAVEN_REPO_PASS }} \
            -Ptag="${{ env.VERSION }}" ;

      - name: Update Schema Version Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ inputs.gistID }}
          filename: ${{ env.REPOSITORY_NAME }}-schema.json
          label: Schema Version
          message: ${{ env.VERSION }}
          color: orange

      - name: Upload build results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: results
          retention-days: 1
          path: |
            **/build/reports/**/*
            **/build/libs/**/*
