#Release new docker image to ECR as well as schema (if contains any changes) to Nexus (use for testing ONLY)

name: Release for testing

on:
  workflow_call:
    outputs:
      version:
        description: Version number of the image released to ECR
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IS_DEFAULT_BRANCH: ${{ contains('refs/heads/main, refs/heads/master', github.ref) }}
      secrets: ${{ toJSON(secrets) }}
    outputs:
      version: ${{ steps.format-version.outputs.version }}
    steps:
      - id: setup-build-environment
        name: "Setup build environment"
        uses: sympower/sympower-composite-actions/setup-build-environment@2024.05.13.10.55-f71759a
        with:
          secrets: ${{ env.secrets }}
      - id: format-version
        name: "Format version"
        uses: sympower/sympower-composite-actions/format-version@2024.05.13.10.55-f71759a
        with:
          style-as-release: ${{ env.IS_DEFAULT_BRANCH }}
      - id: build-and-upload-docker-image
        name: "Build and upload Docker Image"
        uses: sympower/sympower-composite-actions/build-and-upload-docker-image@2024.05.13.10.55-f71759a
        with:
          version: ${{ steps.format-version.outputs.version }}
      - id: upload-build-artifacts
        name: "Upload build artifacts"
        if: always()
        uses: sympower/sympower-composite-actions/upload-build-artifacts@2024.05.13.10.55-f71759a