name: Run tests

on:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      MAVEN_REPO_PUBLIC_URL:
        required: true
      MAVEN_REPO_SNAPSHOTS_URL:
        required: true
      MAVEN_REPO_RELEASES_URL:
        required: true
      MAVEN_REPO_USER:
        required: true
      MAVEN_REPO_PASS:
        required: true
      DOCKER_REGISTRY_HOST:
        required: true
      PACT_BROKER_BASE_URL:
        required: true
      PACT_BROKER_USERNAME:
        required: true
      PACT_BROKER_PASSWORD:
        required: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Run unit tests
        run: |
          set -ue ;
          ./gradlew test --parallel --continue --stacktrace \
            -PsympowerMavenRepoPublicUrl="${{ secrets.MAVEN_REPO_PUBLIC_URL }}" \
            -PsympowerMavenRepoSnapshotsUrl="${{ secrets.MAVEN_REPO_SNAPSHOTS_URL }}" \
            -PsympowerMavenRepoReleasesUrl="${{ secrets.MAVEN_REPO_RELEASES_URL }}" \
            -PsympowerMavenRepoUsername="${{ secrets.MAVEN_REPO_USER }}" \
            -PsympowerMavenRepoPassword="${{ secrets.MAVEN_REPO_PASS }}" \
            -Ppactbroker.url="${{ secrets.PACT_BROKER_BASE_URL }}" \
            -Ppactbroker.auth.username="${{ secrets.PACT_BROKER_USERNAME }}" \
            -Ppactbroker.auth.password="${{ secrets.PACT_BROKER_PASSWORD }}" ;

      - name: Unit test report
        uses: phoenix-actions/test-reporting@v12
        continue-on-error: true
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        with:
          name: Unit test results
          path: '**/test-results/test/*.xml'
          reporter: java-junit
          fail-on-error: false
          output-to: step-summary

      - name: Run behaviour tests
        run: |
          set -ue ;
          ./gradlew behaviourTest --parallel --continue --stacktrace \
            -PsympowerMavenRepoPublicUrl="${{ secrets.MAVEN_REPO_PUBLIC_URL }}" \
            -PsympowerMavenRepoSnapshotsUrl="${{ secrets.MAVEN_REPO_SNAPSHOTS_URL }}" \
            -PsympowerMavenRepoReleasesUrl="${{ secrets.MAVEN_REPO_RELEASES_URL }}" \
            -PsympowerMavenRepoUsername="${{ secrets.MAVEN_REPO_USER }}" \
            -PsympowerMavenRepoPassword="${{ secrets.MAVEN_REPO_PASS }}" \
            -Ppactbroker.url="${{ secrets.PACT_BROKER_BASE_URL }}" \
            -Ppactbroker.auth.username="${{ secrets.PACT_BROKER_USERNAME }}" \
            -Ppactbroker.auth.password="${{ secrets.PACT_BROKER_PASSWORD }}" ;

      - name: Behaviour test report
        uses: phoenix-actions/test-reporting@v12
        continue-on-error: true
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        with:
          name: Behaviour test results
          path: '**/test-results/behaviourTest/*.xml'
          reporter: java-junit
          fail-on-error: false
          output-to: step-summary

      - name: Run integration tests
        run: |
          set -ue ;
          ./gradlew integrationTest --parallel --continue --stacktrace \
            -PsympowerMavenRepoPublicUrl="${{ secrets.MAVEN_REPO_PUBLIC_URL }}" \
            -PsympowerMavenRepoSnapshotsUrl="${{ secrets.MAVEN_REPO_SNAPSHOTS_URL }}" \
            -PsympowerMavenRepoReleasesUrl="${{ secrets.MAVEN_REPO_RELEASES_URL }}" \
            -PsympowerMavenRepoUsername="${{ secrets.MAVEN_REPO_USER }}" \
            -PsympowerMavenRepoPassword="${{ secrets.MAVEN_REPO_PASS }}" \
            -Ppactbroker.url="${{ secrets.PACT_BROKER_BASE_URL }}" \
            -Ppactbroker.auth.username="${{ secrets.PACT_BROKER_USERNAME }}" \
            -Ppactbroker.auth.password="${{ secrets.PACT_BROKER_PASSWORD }}" ;

      - name: Integration test report
        uses: phoenix-actions/test-reporting@v12
        continue-on-error: true
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        with:
          name: Integration test results
          path: '**/test-results/integrationTest/*.xml'
          reporter: java-junit
          fail-on-error: false
          output-to: step-summary

      - name: Create test reports
        run: |
          set -ue ;
          ./gradlew testCodeCoverageReport behaviourTestCodeCoverageReport integrationTestCodeCoverageReport jacocoTestReport -x test -x behaviourTest -x integrationTest --parallel --continue --stacktrace \
            -PsympowerMavenRepoPublicUrl="${{ secrets.MAVEN_REPO_PUBLIC_URL }}" \
            -PsympowerMavenRepoSnapshotsUrl="${{ secrets.MAVEN_REPO_SNAPSHOTS_URL }}" \
            -PsympowerMavenRepoReleasesUrl="${{ secrets.MAVEN_REPO_RELEASES_URL }}" \
            -PsympowerMavenRepoUsername="${{ secrets.MAVEN_REPO_USER }}" \
            -PsympowerMavenRepoPassword="${{ secrets.MAVEN_REPO_PASS }}" \
            -Ppactbroker.url="${{ secrets.PACT_BROKER_BASE_URL }}" \
            -Ppactbroker.auth.username="${{ secrets.PACT_BROKER_USERNAME }}" \
            -Ppactbroker.auth.password="${{ secrets.PACT_BROKER_PASSWORD }}" ;

      - uses: actions/upload-artifact@v2
        with:
          name: testReports
          path: service/build/reports/jacoco/