# Trigger a specified test module in activating-flexibility-tests

name: Trigger test suite

on:
  workflow_call:
    inputs:
      test-to-trigger:
        description: 'Which test to trigger, e.g., system-activation'
        type: string
        required: true
      service-name:
        description: 'Name of the Docker image of the service to run the test for'
        type: string
        required: true
      service-version:
        description: 'Version of the Docker image of the service to run the test for'
        type: string
        required: true
      comment-downstream-url:
        description: 'Downstream url where to the trigger will add a comment with a link to the started workflow'
        required: false
        type: string
    secrets:
      TEST_TRIGGER_APP_ID:
        required: true
      TEST_TRIGGER_APP_KEY:
        required: true

jobs:
  trigger-test-suite:
    name: Trigger test suite
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.TEST_TRIGGER_APP_ID }}
          private_key: ${{ secrets.TEST_TRIGGER_APP_KEY }}

      - uses: convictional/trigger-workflow-and-wait@v1.6.5
        with:
          owner: sympower
          repo: activating-flexibility-tests
          ref: main
          workflow_file_name: remote-test-trigger.yml
          client_payload: >-
            { 
              "test-to-trigger": "${{ inputs.test-to-trigger }}", 
              "${{ inputs.service-name }}-version": "${{ inputs.service-version }}" 
            }
          github_token: ${{ steps.generate-token.outputs.token }}
          comment_downstream_url: ${{ inputs.comment-downstream-url }}
